spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=GMT%2B8&userSSL=false&characterEncoding=utf-8
    username: root
    password: 12345
  redis:
    port: 6379
    host: localhost
    password: 12345
    database: 0
  application:
    name: login-service-producer
  cloud:
    nacos:
      server-addr:
        localhost:8848

server:
  port: 8081
