spring:
  application:
    name: client-consumer
  cloud:
    nacos:
      server-addr: 47.106.185.49:8848
    sentinel:
      transport:
        dashboard: localhost:8085
        port: 8719 #控制台与应用交互的端口

management:
  endpoints:
    web:
      exposure:
        include: '*'

#开启OpenFeign使用OkHttp作为底层的client
feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        loggerLevel: full
  sentinel:
    enabled: true

server:
  port: 801